"""empty message

Revision ID: cc02a6a32597
Revises: 17e328106bdc
Create Date: 2025-11-22 22:32:04.991851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc02a6a32597'
down_revision: Union[str, Sequence[str], None] = '17e328106bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctionitem', schema=None) as batch_op:
        batch_op.drop_column('starting_price')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctionitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
